import { DebridioChannel } from "./types";

// Generated from Debridio catalog fetch on 2026-04-14. Regenerate by running:
//   curl -s "https://tv.lb.debridio.com/<token>/catalog/tv/ca.json" | ...
// Keep this as the source of truth for which Debridio channels we try to enrich.

export const DEBRIDIO_CHANNELS: readonly DebridioChannel[] = [
  // --- CA (21 channels) ---
  { id: "debtv:ca-canalsavoir", name: "Canal Savoir", tvgId: "Canal Savoir.ca", country: "ca" },
  { id: "debtv:ca-cp24", name: "CP24", tvgId: "CP24.ca", country: "ca" },
  { id: "debtv:ca-cpac", name: "CPAC", tvgId: "CPAC.ca", country: "ca" },
  { id: "debtv:ca-espntheocho", name: "ESPN The Ocho", tvgId: "ESPN The Ocho.ca", country: "ca" },
  { id: "debtv:ca-gameplus", name: "Game+", tvgId: "Game+.ca", country: "ca" },
  { id: "debtv:ca-lovenature", name: "Love Nature", tvgId: "Love Nature.ca", country: "ca" },
  { id: "debtv:ca-sportsnet360", name: "Sportsnet 360", tvgId: "Sportsnet 360.ca", country: "ca" },
  { id: "debtv:ca-sportsneteast", name: "Sportsnet East", tvgId: "Sportsnet East.ca", country: "ca" },
  { id: "debtv:ca-sportsnetone", name: "Sportsnet One", tvgId: "Sportsnet One.ca", country: "ca" },
  { id: "debtv:ca-sportsnetontario", name: "Sportsnet Ontario", tvgId: "Sportsnet Ontario.ca", country: "ca" },
  { id: "debtv:ca-sportsnetpacific", name: "Sportsnet Pacific", tvgId: "Sportsnet Pacific.ca", country: "ca" },
  { id: "debtv:ca-sportsnetwest", name: "Sportsnet West", tvgId: "Sportsnet West.ca", country: "ca" },
  { id: "debtv:ca-sportsnetworld", name: "Sportsnet World", tvgId: "Sportsnet World.ca", country: "ca" },
  { id: "debtv:ca-tsc", name: "TSC", tvgId: "TSC.ca", country: "ca" },
  { id: "debtv:ca-tsn1", name: "TSN 1", tvgId: "TSN 1.ca", country: "ca" },
  { id: "debtv:ca-tsn2", name: "TSN 2", tvgId: "TSN 2.ca", country: "ca" },
  { id: "debtv:ca-tsn3", name: "TSN 3", tvgId: "TSN 3.ca", country: "ca" },
  { id: "debtv:ca-tsn4", name: "TSN 4", tvgId: "TSN 4.ca", country: "ca" },
  { id: "debtv:ca-tsn5", name: "TSN 5", tvgId: "TSN 5.ca", country: "ca" },
  { id: "debtv:ca-wildtv", name: "Wild TV", tvgId: "Wild TV.ca", country: "ca" },
  { id: "debtv:ca-wnetwork", name: "W Network", tvgId: "W Network.ca", country: "ca" },
  // --- USA (188 channels) ---
  { id: "debtv:usa-5starmax", name: "5StarMax", tvgId: "5StarMax.usa", country: "usa" },
  { id: "debtv:usa-abc", name: "ABC", tvgId: "ABC.usa", country: "usa" },
  { id: "debtv:usa-abcnews", name: "ABC News", tvgId: "ABC News.usa", country: "usa" },
  { id: "debtv:usa-accnetwork", name: "ACC Network", tvgId: "ACC Network.usa", country: "usa" },
  { id: "debtv:usa-ae", name: "A&E", tvgId: "A&E.usa", country: "usa" },
  { id: "debtv:usa-altitudesports", name: "Altitude Sports", tvgId: "Altitude Sports.usa", country: "usa" },
  { id: "debtv:usa-amc", name: "AMC", tvgId: "AMC.usa", country: "usa" },
  { id: "debtv:usa-americancrimes", name: "American Crimes", tvgId: "American Crimes.usa", country: "usa" },
  { id: "debtv:usa-americateve", name: "AmericaTeve", tvgId: "AmericaTeve.usa", country: "usa" },
  { id: "debtv:usa-animalplanet", name: "Animal Planet", tvgId: "Animal Planet.usa", country: "usa" },
  { id: "debtv:usa-axstv", name: "AXS Tv", tvgId: "AXS Tv.usa", country: "usa" },
  { id: "debtv:usa-aztecainternacional", name: "Azteca Internacional", tvgId: "Azteca Internacional.usa", country: "usa" },
  { id: "debtv:usa-bbcamerica", name: "BBC America", tvgId: "BBC America.usa", country: "usa" },
  { id: "debtv:usa-bbcworldnews", name: "BBC World News", tvgId: "BBC World News.usa", country: "usa" },
  { id: "debtv:usa-beinsports", name: "Bein Sports", tvgId: "Bein Sports.usa", country: "usa" },
  { id: "debtv:usa-bet", name: "BET", tvgId: "BET.usa", country: "usa" },
  { id: "debtv:usa-betgospel", name: "BET Gospel", tvgId: "BET Gospel.usa", country: "usa" },
  { id: "debtv:usa-bether", name: "BET Her", tvgId: "BET Her.usa", country: "usa" },
  { id: "debtv:usa-bigtennetwork", name: "Big Ten Network", tvgId: "Big Ten Network.usa", country: "usa" },
  { id: "debtv:usa-bloomberg", name: "Bloomberg", tvgId: "Bloomberg.usa", country: "usa" },
  { id: "debtv:usa-boomerang", name: "Boomerang", tvgId: "Boomerang.usa", country: "usa" },
  { id: "debtv:usa-bouncetv", name: "Bounce TV", tvgId: "Bounce TV.usa", country: "usa" },
  { id: "debtv:usa-bravo", name: "Bravo", tvgId: "Bravo.usa", country: "usa" },
  { id: "debtv:usa-buzzr", name: "Buzzr", tvgId: "Buzzr.usa", country: "usa" },
  { id: "debtv:usa-cartoonnetwork", name: "Cartoon Network", tvgId: "Cartoon Network.usa", country: "usa" },
  { id: "debtv:usa-cbs", name: "CBS", tvgId: "CBS.usa", country: "usa" },
  { id: "debtv:usa-cbssportsgolazonetwork", name: "CBS Sports Golazo Network", tvgId: "CBS Sports Golazo Network.usa", country: "usa" },
  { id: "debtv:usa-cbssportshq", name: "CBS Sports HQ", tvgId: "CBS Sports HQ.usa", country: "usa" },
  { id: "debtv:usa-cbssportsnetwork", name: "CBS Sports Network", tvgId: "CBS Sports Network.usa", country: "usa" },
  { id: "debtv:usa-chicagosportsnetwork", name: "Chicago Sports Network", tvgId: "Chicago Sports Network.usa", country: "usa" },
  { id: "debtv:usa-cinemaxeast", name: "Cinemax East", tvgId: "Cinemax East.usa", country: "usa" },
  { id: "debtv:usa-cinemaxmoremax", name: "Cinemax MoreMax", tvgId: "Cinemax MoreMax.usa", country: "usa" },
  { id: "debtv:usa-cinemaxthrillermax", name: "Cinemax Thriller Max", tvgId: "Cinemax Thriller Max.usa", country: "usa" },
  { id: "debtv:usa-cinemaxwest", name: "Cinemax West", tvgId: "Cinemax West.usa", country: "usa" },
  { id: "debtv:usa-cleotv", name: "Cleo TV", tvgId: "Cleo TV.usa", country: "usa" },
  { id: "debtv:usa-cmt", name: "CMT", tvgId: "CMT.usa", country: "usa" },
  { id: "debtv:usa-cnbc", name: "CNBC", tvgId: "CNBC.usa", country: "usa" },
  { id: "debtv:usa-cnn", name: "CNN", tvgId: "CNN.usa", country: "usa" },
  { id: "debtv:usa-comedycentral", name: "Comedy Central", tvgId: "Comedy Central.usa", country: "usa" },
  { id: "debtv:usa-comettv", name: "Comet TV", tvgId: "Comet TV.usa", country: "usa" },
  { id: "debtv:usa-cookingchannel", name: "Cooking Channel", tvgId: "Cooking Channel.usa", country: "usa" },
  { id: "debtv:usa-crimeandinvestigationnetwork", name: "Crime and Investigation Network", tvgId: "Crime and Investigation Network.usa", country: "usa" },
  { id: "debtv:usa-cspan", name: "C-SPAN", tvgId: "C-SPAN.usa", country: "usa" },
  { id: "debtv:usa-destinationamerica", name: "Destination America", tvgId: "Destination America.usa", country: "usa" },
  { id: "debtv:usa-discovery", name: "Discovery", tvgId: "Discovery.usa", country: "usa" },
  { id: "debtv:usa-discoveryfamily", name: "Discovery Family", tvgId: "Discovery Family.usa", country: "usa" },
  { id: "debtv:usa-discoverylife", name: "Discovery Life", tvgId: "Discovery Life.usa", country: "usa" },
  { id: "debtv:usa-disneychannel", name: "Disney Channel", tvgId: "Disney Channel.usa", country: "usa" },
  { id: "debtv:usa-disneyjr", name: "Disney Jr.", tvgId: "Disney Jr..usa", country: "usa" },
  { id: "debtv:usa-disneyxd", name: "Disney XD", tvgId: "Disney XD.usa", country: "usa" },
  { id: "debtv:usa-eentertainmenttelevision", name: "E! Entertainment Television", tvgId: "E! Entertainment Television.usa", country: "usa" },
  { id: "debtv:usa-epix", name: "EPIX", tvgId: "EPIX.usa", country: "usa" },
  { id: "debtv:usa-epix2", name: "EPIX 2", tvgId: "EPIX 2.usa", country: "usa" },
  { id: "debtv:usa-epixdrivein", name: "EPIX Drive-In", tvgId: "EPIX Drive-In.usa", country: "usa" },
  { id: "debtv:usa-epixhits", name: "EPIX Hits", tvgId: "EPIX Hits.usa", country: "usa" },
  { id: "debtv:usa-espn", name: "ESPN", tvgId: "ESPN.usa", country: "usa" },
  { id: "debtv:usa-espn2", name: "ESPN 2", tvgId: "ESPN 2.usa", country: "usa" },
  { id: "debtv:usa-espnnews", name: "ESPN News", tvgId: "ESPN News.usa", country: "usa" },
  { id: "debtv:usa-espnu", name: "ESPN U", tvgId: "ESPN U.usa", country: "usa" },
  { id: "debtv:usa-estrellatv", name: "Estrella TV", tvgId: "Estrella TV.usa", country: "usa" },
  { id: "debtv:usa-fanduelsportsnetwork", name: "FanDuel Sports Network", tvgId: "FanDuel Sports Network.usa", country: "usa" },
  { id: "debtv:usa-foodnetwork", name: "Food Network", tvgId: "Food Network.usa", country: "usa" },
  { id: "debtv:usa-foxbusinessnetwork", name: "Fox Business Network", tvgId: "Fox Business Network.usa", country: "usa" },
  { id: "debtv:usa-foxeast", name: "Fox", tvgId: "Fox.usa", country: "usa" },
  { id: "debtv:usa-foxnews", name: "Fox News", tvgId: "Fox News.usa", country: "usa" },
  { id: "debtv:usa-foxsports", name: "Fox Sports", tvgId: "Fox Sports.usa", country: "usa" },
  { id: "debtv:usa-fuse", name: "Fuse", tvgId: "Fuse.usa", country: "usa" },
  { id: "debtv:usa-fx", name: "FX", tvgId: "FX.usa", country: "usa" },
  { id: "debtv:usa-fxmovie", name: "FX Movie", tvgId: "FX Movie.usa", country: "usa" },
  { id: "debtv:usa-fxx", name: "FXX", tvgId: "FXX.usa", country: "usa" },
  { id: "debtv:usa-fyi", name: "FYI", tvgId: "FYI.usa", country: "usa" },
  { id: "debtv:usa-galavision", name: "Galavision", tvgId: "Galavision.usa", country: "usa" },
  { id: "debtv:usa-gameshownetwork", name: "Game Show Network", tvgId: "Game Show Network.usa", country: "usa" },
  { id: "debtv:usa-gettv", name: "Get TV", tvgId: "Get TV.usa", country: "usa" },
  { id: "debtv:usa-golfchannel", name: "Golf Channel", tvgId: "Golf Channel.usa", country: "usa" },
  { id: "debtv:usa-goltv", name: "Gol TV", tvgId: "Gol TV.usa", country: "usa" },
  { id: "debtv:usa-grittv", name: "GRIT TV", tvgId: "GRIT TV.usa", country: "usa" },
  { id: "debtv:usa-hallmarkchannel", name: "Hallmark Channel", tvgId: "Hallmark Channel.usa", country: "usa" },
  { id: "debtv:usa-hallmarkdrama", name: "Hallmark Drama", tvgId: "Hallmark Drama.usa", country: "usa" },
  { id: "debtv:usa-hallmarkmoviesmysteries", name: "Hallmark Movies & Mysteries", tvgId: "Hallmark Movies & Mysteries.usa", country: "usa" },
  { id: "debtv:usa-hbo", name: "HBO", tvgId: "HBO.usa", country: "usa" },
  { id: "debtv:usa-hbo2", name: "HBO 2", tvgId: "HBO 2.usa", country: "usa" },
  { id: "debtv:usa-hbocomedy", name: "HBO Comedy", tvgId: "HBO Comedy.usa", country: "usa" },
  { id: "debtv:usa-hbofamily", name: "HBO Family", tvgId: "HBO Family.usa", country: "usa" },
  { id: "debtv:usa-hbolatino", name: "HBO Latino", tvgId: "HBO Latino.usa", country: "usa" },
  { id: "debtv:usa-hbosignature", name: "HBO Signature", tvgId: "HBO Signature.usa", country: "usa" },
  { id: "debtv:usa-hbozone", name: "HBO Zone", tvgId: "HBO Zone.usa", country: "usa" },
  { id: "debtv:usa-hgtv", name: "HGTV", tvgId: "HGTV.usa", country: "usa" },
  { id: "debtv:usa-history", name: "History", tvgId: "History.usa", country: "usa" },
  { id: "debtv:usa-hln", name: "HLN", tvgId: "HLN.usa", country: "usa" },
  { id: "debtv:usa-hsn", name: "HSN", tvgId: "HSN.usa", country: "usa" },
  { id: "debtv:usa-id", name: "ID", tvgId: "ID.usa", country: "usa" },
  { id: "debtv:usa-ifc", name: "IFC", tvgId: "IFC.usa", country: "usa" },
  { id: "debtv:usa-insp", name: "INSP", tvgId: "INSP.usa", country: "usa" },
  { id: "debtv:usa-iontv", name: "Ion TV", tvgId: "Ion TV.usa", country: "usa" },
  { id: "debtv:usa-lafftv", name: "Laff TV", tvgId: "Laff TV.usa", country: "usa" },
  { id: "debtv:usa-lifetime", name: "Lifetime", tvgId: "Lifetime.usa", country: "usa" },
  { id: "debtv:usa-lifetimemovies", name: "Lifetime Movies", tvgId: "Lifetime Movies.usa", country: "usa" },
  { id: "debtv:usa-logo", name: "Logo", tvgId: "Logo.usa", country: "usa" },
  { id: "debtv:usa-lovenature", name: "Love Nature", tvgId: "Love Nature.usa", country: "usa" },
  { id: "debtv:usa-magnolianetwork", name: "Magnolia Network", tvgId: "Magnolia Network.usa", country: "usa" },
  { id: "debtv:usa-marqueesportsnetwork", name: "Marquee Sports Network", tvgId: "Marquee Sports Network.usa", country: "usa" },
  { id: "debtv:usa-mavtv", name: "Mav TV", tvgId: "Mav TV.usa", country: "usa" },
  { id: "debtv:usa-megatv", name: "MegaTv", tvgId: "MegaTv.usa", country: "usa" },
  { id: "debtv:usa-metv", name: "Me TV", tvgId: "Me TV.usa", country: "usa" },
  { id: "debtv:usa-metvtoons", name: "Me TV Toons", tvgId: "Me TV Toons.usa", country: "usa" },
  { id: "debtv:usa-militaryhistory", name: "Military History", tvgId: "Military History.usa", country: "usa" },
  { id: "debtv:usa-mlbnetwork", name: "MLB Network", tvgId: "MLB Network.usa", country: "usa" },
  { id: "debtv:usa-motortrend", name: "Motor Trend", tvgId: "Motor Trend.usa", country: "usa" },
  { id: "debtv:usa-msg", name: "MSG", tvgId: "MSG.usa", country: "usa" },
  { id: "debtv:usa-msnbc", name: "MSNBC", tvgId: "MSNBC.usa", country: "usa" },
  { id: "debtv:usa-mtv", name: "MTV", tvgId: "MTV.usa", country: "usa" },
  { id: "debtv:usa-mtv2", name: "MTV 2", tvgId: "MTV 2.usa", country: "usa" },
  { id: "debtv:usa-mtvlive", name: "MTV Live", tvgId: "MTV Live.usa", country: "usa" },
  { id: "debtv:usa-natgeo", name: "National Geographic", tvgId: "National Geographic.usa", country: "usa" },
  { id: "debtv:usa-natgeowild", name: "Nat Geo Wild", tvgId: "Nat Geo Wild.usa", country: "usa" },
  { id: "debtv:usa-nbatv", name: "NBA TV", tvgId: "NBA TV.usa", country: "usa" },
  { id: "debtv:usa-nbc", name: "NBC", tvgId: "NBC.usa", country: "usa" },
  { id: "debtv:usa-nbcsportsnetwork", name: "NBC Sports Network", tvgId: "NBC Sports Network.usa", country: "usa" },
  { id: "debtv:usa-nesn", name: "nesn", tvgId: "nesn.usa", country: "usa" },
  { id: "debtv:usa-newsnation", name: "News Nation", tvgId: "News Nation.usa", country: "usa" },
  { id: "debtv:usa-nflnetwork", name: "NFL Network", tvgId: "NFL Network.usa", country: "usa" },
  { id: "debtv:usa-nflredzone", name: "NFL RedZone", tvgId: "NFL RedZone.usa", country: "usa" },
  { id: "debtv:usa-nhlnetwork", name: "NHL Network", tvgId: "NHL Network.usa", country: "usa" },
  { id: "debtv:usa-nickelodeon", name: "Nickelodeon", tvgId: "Nickelodeon.usa", country: "usa" },
  { id: "debtv:usa-nickjr", name: "Nick Jr.", tvgId: "Nick Jr..usa", country: "usa" },
  { id: "debtv:usa-nicktoons", name: "Nicktoons", tvgId: "Nicktoons.usa", country: "usa" },
  { id: "debtv:usa-outdoorchannel", name: "Outdoor Channel", tvgId: "Outdoor Channel.usa", country: "usa" },
  { id: "debtv:usa-outsidetv", name: "Outside TV", tvgId: "Outside TV.usa", country: "usa" },
  { id: "debtv:usa-ovation", name: "Ovation", tvgId: "Ovation.usa", country: "usa" },
  { id: "debtv:usa-own", name: "OWN", tvgId: "OWN.usa", country: "usa" },
  { id: "debtv:usa-oxygen", name: "Oxygen", tvgId: "Oxygen.usa", country: "usa" },
  { id: "debtv:usa-paramountnetwork", name: "Paramount Network", tvgId: "Paramount Network.usa", country: "usa" },
  { id: "debtv:usa-pbskids", name: "PBS Kids", tvgId: "PBS Kids.usa", country: "usa" },
  { id: "debtv:usa-poptv", name: "Pop TV", tvgId: "Pop TV.usa", country: "usa" },
  { id: "debtv:usa-qvc", name: "QVC", tvgId: "QVC.usa", country: "usa" },
  { id: "debtv:usa-reelz", name: "Reelz", tvgId: "Reelz.usa", country: "usa" },
  { id: "debtv:usa-science", name: "Science", tvgId: "Science.usa", country: "usa" },
  { id: "debtv:usa-scrippsnews", name: "Scripps News", tvgId: "Scripps News.usa", country: "usa" },
  { id: "debtv:usa-secnetwork", name: "SEC Network", tvgId: "SEC Network.usa", country: "usa" },
  { id: "debtv:usa-showtime", name: "Showtime", tvgId: "Showtime.usa", country: "usa" },
  { id: "debtv:usa-showtime2", name: "Showtime 2", tvgId: "Showtime 2.usa", country: "usa" },
  { id: "debtv:usa-showtimeextreme", name: "Showtime Extreme", tvgId: "Showtime Extreme.usa", country: "usa" },
  { id: "debtv:usa-showtimewomen", name: "Showtime Women", tvgId: "Showtime Women.usa", country: "usa" },
  { id: "debtv:usa-smithsonianchannel", name: "Smithsonian Channel", tvgId: "Smithsonian Channel.usa", country: "usa" },
  { id: "debtv:usa-sny", name: "sny", tvgId: "sny.usa", country: "usa" },
  { id: "debtv:usa-sonycine", name: "Sony Cine", tvgId: "Sony Cine.usa", country: "usa" },
  { id: "debtv:usa-sonymoviechannel", name: "Sony Movie Channel", tvgId: "Sony Movie Channel.usa", country: "usa" },
  { id: "debtv:usa-spectrumsportsnet", name: "Spectrum Sportsnet", tvgId: "Spectrum Sportsnet.usa", country: "usa" },
  { id: "debtv:usa-sportsnetpittsburgh", name: "Sportsnet Pittsburgh", tvgId: "Sportsnet Pittsburgh.usa", country: "usa" },
  { id: "debtv:usa-starz", name: "Starz", tvgId: "Starz.usa", country: "usa" },
  { id: "debtv:usa-starzcinema", name: "Starz Cinema", tvgId: "Starz Cinema.usa", country: "usa" },
  { id: "debtv:usa-starzcomedy", name: "Starz Comedy", tvgId: "Starz Comedy.usa", country: "usa" },
  { id: "debtv:usa-starzedge", name: "Starz Edge", tvgId: "Starz Edge.usa", country: "usa" },
  { id: "debtv:usa-starzencore", name: "Starz Encore", tvgId: "Starz Encore.usa", country: "usa" },
  { id: "debtv:usa-starzencoreaction", name: "Starz Encore Action", tvgId: "Starz Encore Action.usa", country: "usa" },
  { id: "debtv:usa-starzencoreclassic", name: "Starz Encore Classic", tvgId: "Starz Encore Classic.usa", country: "usa" },
  { id: "debtv:usa-sundance", name: "Sundance", tvgId: "Sundance.usa", country: "usa" },
  { id: "debtv:usa-swimrewind", name: "Swim Rewind", tvgId: "Swim Rewind.usa", country: "usa" },
  { id: "debtv:usa-syfy", name: "SyFy", tvgId: "SyFy.usa", country: "usa" },
  { id: "debtv:usa-tbs", name: "TBS", tvgId: "TBS.usa", country: "usa" },
  { id: "debtv:usa-tcm", name: "TCM", tvgId: "TCM.usa", country: "usa" },
  { id: "debtv:usa-teennick", name: "Teen Nick", tvgId: "Teen Nick.usa", country: "usa" },
  { id: "debtv:usa-telemundo", name: "Telemundo", tvgId: "Telemundo.usa", country: "usa" },
  { id: "debtv:usa-tennischannel", name: "Tennis Channel", tvgId: "Tennis Channel.usa", country: "usa" },
  { id: "debtv:usa-thecw", name: "The CW", tvgId: "The CW.usa", country: "usa" },
  { id: "debtv:usa-theweatherchannel", name: "The Weather Channel", tvgId: "The Weather Channel.usa", country: "usa" },
  { id: "debtv:usa-tlc", name: "TLC", tvgId: "TLC.usa", country: "usa" },
  { id: "debtv:usa-tnt", name: "TNT", tvgId: "TNT.usa", country: "usa" },
  { id: "debtv:usa-toonamiaftermath", name: "Toonami Aftermath", tvgId: "Toonami Aftermath.usa", country: "usa" },
  { id: "debtv:usa-travelchannel", name: "Travel Channel", tvgId: "Travel Channel.usa", country: "usa" },
  { id: "debtv:usa-trutv", name: "Tru TV", tvgId: "Tru TV.usa", country: "usa" },
  { id: "debtv:usa-tudn", name: "TUDN", tvgId: "TUDN.usa", country: "usa" },
  { id: "debtv:usa-tvg", name: "TVG", tvgId: "TVG.usa", country: "usa" },
  { id: "debtv:usa-tvland", name: "TV Land", tvgId: "TV Land.usa", country: "usa" },
  { id: "debtv:usa-tvone", name: "TV One", tvgId: "TV One.usa", country: "usa" },
  { id: "debtv:usa-ufctv", name: "UFC", tvgId: "UFC.usa", country: "usa" },
  { id: "debtv:usa-unimas", name: "UniMas", tvgId: "UniMas.usa", country: "usa" },
  { id: "debtv:usa-univision", name: "Univision", tvgId: "Univision.usa", country: "usa" },
  { id: "debtv:usa-usanetwork", name: "USA Network", tvgId: "USA Network.usa", country: "usa" },
  { id: "debtv:usa-vh1", name: "VH1", tvgId: "VH1.usa", country: "usa" },
  { id: "debtv:usa-viceland", name: "Viceland", tvgId: "Viceland.usa", country: "usa" },
  { id: "debtv:usa-wetv", name: "We TV", tvgId: "We TV.usa", country: "usa" },
  { id: "debtv:usa-wgn", name: "WGN", tvgId: "WGN.usa", country: "usa" },
  { id: "debtv:usa-willowtv", name: "Willow TV", tvgId: "Willow TV.usa", country: "usa" },
  { id: "debtv:usa-willowxtra", name: "Willow XTRA", tvgId: "Willow XTRA.usa", country: "usa" },
  { id: "debtv:usa-worldfishingnetwork", name: "World Fishing Network", tvgId: "World Fishing Network.usa", country: "usa" },
  { id: "debtv:usa-yesnetwork", name: "Yes Network", tvgId: "Yes Network.usa", country: "usa" },
];
